# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push:
    branches:    
      - 'openforms'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
        # Tis creates a settingx.xml with the credentials
        server-id: jfrog # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: apiuser
        server-password: apitoken
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Change group
#      run: find . -type f -name 'pom.xml' -exec sed -i "s/<groupId>wonder/<groupId>ofwonder/g" {} \;

    - name: Build with Maven
      run: mvn -B package -s $GITHUB_WORKSPACE/settings.xml

    - name: Publish to jFrog
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        apiuser: github-actions-bot
        apitoken: ${{ secrets.JFROG_ACTIONS_TOKEN }}